500 server internal error
502 Gateway error
503 Service Not Implemented
403 Access Forbidden
400 Bad Request
401 Unauthorized -> failed to provide correct entitlement
403 Forbidden -> does not has corrent access
406 Not Acceptable -> Resource generated by Server not accept by client according to 'accept' field in the request header
404 Not Found
304 Not Modified